version: 2.1

jobs:
  build:
    working_directory: ~/github-statistics

    docker:
      - image: cimg/openjdk:21.0-browsers

    steps:
      - checkout

      - run:
          name: Spotless check
          command: mvn -f backend/pom.xml spotless:check

      - run:
          name: Test and build
          command: mvn verify

workflows:
  main:
    jobs:
      - build