version: 2.1

jobs:
  build:
    working_directory: ~/cache-machine

    docker:
      - image: cimg/openjdk:21.0-browsers

    steps:
      - checkout

      - run: mvn verify

workflows:
  main:
    jobs:
      - build