version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:21.0-browsers

jobs:
  build-frontend:
    executor: default-executor
    working_directory: ~/github-statistics/frontend
    steps:
      - checkout:
          path: ~/github-statistics
      - restore_cache:
          keys:
            - frontend-{{ checksum "package-lock.json" }}
      - run:
          name: Install deps
          command: npm ci
      - run:
          name: Ng Lint
          command: npm run lint
      - save_cache:
          paths:
            - ~/github-statistics/frontend/node_modules
          key: frontend-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: mvn clean package

  build-backend:
    executor: default-executor
    working_directory: ~/github-statistics/backend
    steps:
      - checkout:
          path: ~/github-statistics
      - restore_cache:
          keys:
            - act-pl-{{ checksum "pom.xml" }}
      - run:
          name: Spotless check
          command: mvn spotless:check
      - run:
          name: Test and build
          command: mvn clean verify
      - save_cache:
          paths:
            - ~/.m2
          key: act-pl-{{ checksum "pom.xml" }}

  delivery:
    executor: default-executor
    working_directory: ~/github-statistics/delivery
    steps:
      - checkout

workflows:
  main:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master
      - build-backend:
          filters:
            branches:
              only: master
      - delivery:
          requires:
            - build-frontend
            - build-backend
          filters:
            branches:
              only: master