version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:21.0-browsers

jobs:
  build:
    executor: default-executor
    working_directory: ~/github-statistics
    steps:
      - checkout
      - run:
          name: Spotless check
          command: mvn -f backend/pom.xml spotless:check
      - run:
          name: Install deps
          command: | 
            cd frontend
            npm install --package-lock
      - run:
          name: Ng Lint
          command: npm run lint
      - run:
          name: Test and build
          command: mvn verify

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master