version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:21.0-browsers

jobs:
  build-frontend:
    executor: default-executor
    working_directory: ~/github-statistics/frontend
    steps:
      - checkout:
          path: ~/github-statistics
      - restore_cache:
          keys:
            - frontend-{{ checksum "package-lock.json" }}
      - run:
          name: Install deps
          command: npm ci
#      - run:
#          name: Ng Lint
#          command: npm run lint
      - save_cache:
          paths:
            - ~/github-statistics/frontend/node_modules
          key: frontend-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: mvn clean install
      - persist_to_workspace:
          root: ~/github-statistics
          paths:
            - frontend/target/*.jar
  build-backend:
    executor: default-executor
    working_directory: ~/github-statistics/backend
    steps:
      - checkout:
          path: ~/github-statistics
      - restore_cache:
          keys:
            - backend-{{ checksum "pom.xml" }}
#      - run:
#          name: Spotless check
#          command: mvn spotless:check
      - run:
          name: Build
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: backend-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ~/github-statistics
          paths:
            - backend/target/*.jar
  delivery:
    executor: default-executor
    working_directory: ~/github-statistics/delivery
    steps:
      - checkout:
          path: ~/github-statistics
      - attach_workspace:
          at: ~/github-statistics
      - run:
          name: Display contents of Maven repository
          command: ls -l ~/github-statistics
      - run:
          name: Set up Maven repository
          command: mkdir -p ~/.m2/repository/dev/graczykmateusz/1.0-SNAPSHOT/
      - run:
          name: Copy frontend JAR
          command: cp ~/github-statistics/frontend/target/*.jar ~/.m2/repository/dev/graczykmateusz/1.0-SNAPSHOT/frontend-1.0-SNAPSHOT.jar
      - run:
          name: Copy backend JAR
          command: cp ~/github-statistics/backend/target/*.jar ~/.m2/repository/dev/graczykmateusz/1.0-SNAPSHOT/backend-1.0-SNAPSHOT.jar
      - run:
          name: Display contents of Maven repository
          command: ls -l ~/.m2/repository/dev/graczykmateusz
      - run:
          name: Build
          command: mvn package
workflows:
  main:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master
      - build-backend:
          filters:
            branches:
              only: master
      - delivery:
          requires:
            - build-frontend
            - build-backend
          filters:
            branches:
              only: master